stringX = str("Hello World")
intX = int(20)
floatX = float(20.5)
complexX = complex(1j)
listX = list(("apple", "banana", "cherry"))	
tupleX = tuple(("apple", "banana", "cherry"))		
rangeX = range(6)		
dictX = dict(name="John", age=36)		
setX = set(("apple", "banana", "cherry"))		
frozensetX = frozenset(("apple", "banana", "cherry"))		
boolX = bool(5)		
bytesX = bytes(5)		
bytearrayX = bytearray(5)		
memoryviewX = memoryview(bytes(5))
print('stringX', stringX)
print('intX', intX)
print('floatX', floatX)
print('complexX', complexX)
print('tupleX', tupleX)
print('rangeX', rangeX)
print('dictX', dictX)
print('setX', setX)
print('frozensetX', frozensetX)
print('boolX', boolX)
print('bytesX', bytesX)
print('bytearrayX', bytearrayX)
print('memoryviewX', memoryviewX)
